# data
data:
  instruct_data: "/Users/naimsassine/Desktop/DSAI/BelgianLawFinetuning/Data/jsonl_files/all_instruct.jsonl"  # Fill
  data: "/Users/naimsassine/Desktop/DSAI/BelgianLawFinetuning/Data/jsonl_files/all_text.jsonl"  # Optionally fill with pretraining data 
  eval_instruct_data: ""  # Optionally fill

# model
model_id_or_path: "/Users/naimsassine/Desktop/DSAI/BelgianLawFinetuning/Code/mistral-7B-Instruct-v0.3"  # Change to downloaded path
lora:
  rank: 64

# optim
seq_len: 32768
batch_size: 1
max_steps: 100
optim:
  lr: 6.e-5
  weight_decay: 0.1
  pct_start: 0.05

# other
seed: 0
log_freq: 1
eval_freq: 100
no_eval: True
ckpt_freq: 100

save_adapters: True  # save only trained LoRA adapters. Set to `False` to merge LoRA adapter into the base model and save full fine-tuned model

run_dir: "/Users/naimsassine/Desktop/DSAI/BelgianLawFinetuning/run_dir"  # Fill

wandb:
  project: "belgianlaw" # your wandb project name
  run_name: "finetuning" # your wandb run name
  key: "" # your wandb api key
  offline: True
